config/routes.rb
Rails.application.routes.draw do
  resources :virements
  resources :transactions
  resources :remboursements
  resources :credits
  resources :compte_clients
  resources :clients
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/compte_client.rb
class CompteClient < ApplicationRecord
  belongs_to :client
  has_many :transactions
end

app/controllers/compte_clients_controller.rb
class CompteClientsController < ApplicationController
  before_action :set_compte_client, only: %i[ show edit update destroy ]

  # GET /compte_clients or /compte_clients.json
  def index
    @compte_clients = CompteClient.all
  end

  # GET /compte_clients/1 or /compte_clients/1.json
  def show
  end

  # GET /compte_clients/new
  def new
    @compte_client = CompteClient.new
  end

  # GET /compte_clients/1/edit
  def edit
  end

  # POST /compte_clients or /compte_clients.json
  def create
    @compte_client = CompteClient.new(compte_client_params)

    respond_to do |format|
      if @compte_client.save
        format.html { redirect_to compte_client_url(@compte_client), notice: "Compte client was successfully created." }
        format.json { render :show, status: :created, location: @compte_client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @compte_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compte_clients/1 or /compte_clients/1.json
  def update
    respond_to do |format|
      if @compte_client.update(compte_client_params)
        format.html { redirect_to compte_client_url(@compte_client), notice: "Compte client was successfully updated." }
        format.json { render :show, status: :ok, location: @compte_client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @compte_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compte_clients/1 or /compte_clients/1.json
  def destroy
    @compte_client.destroy

    respond_to do |format|
      format.html { redirect_to compte_clients_url, notice: "Compte client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compte_client
      @compte_client = CompteClient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def compte_client_params
      params.require(:compte_client).permit(:client_id, :type_compte, :numero_compte, :code_compte, :solde)
    end
end

app/helpers/compte_clients_helper.rb
module CompteClientsHelper
end

app/views/compte_clients/_compte_client.html.erb
<div id="<%= dom_id compte_client %>">
  
  <p>
    <strong>Type compte:</strong>
    <%= compte_client.type_compte %>
  </p>

  <p>
    <strong>Numero compte:</strong>
    <%= compte_client.numero_compte %>
  </p>

  <p>
    <strong>Code compte:</strong>
    <%= compte_client.code_compte %>
  </p>

  <p>
    <strong>Solde:</strong>
    <%= compte_client.solde %>
  </p>

  <p><%= link_to "Editer solde", edit_compte_client_path(compte_client), class: "text-blue-500" %> </p>

</div>

app/views/compte_clients/_form.html.erb
<%= form_with(model: compte_client) do |form| %>
  <% if compte_client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(compte_client.errors.count, "error") %> prohibited this compte_client from being saved:</h2>

      <ul>
        <% compte_client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :client_id, class: "w-full rounded-lg h-[30px] hidden" %>
 
  <div class="grid grid-cols-6 gap-4">

    <div class="col-span-3">
      <%= form.label :type_compte, style: "display: block" %>
      <%= form.select :type_compte, options_for_select([
        ["Courant", "courant"],
        ["Epargne", "epargne"]
      ]), { include_blank: true }, class: "w-full rounded-lg h-[35px]" %>
    </div>

    <div class="col-span-3">
      <%= form.label :numero_compte, style: "display: block" %>
      <%= form.text_field :numero_compte, class: "w-full rounded-lg h-[35px]" %>
    </div>

  </div>

  <div class="grid grid-cols-6 gap-4">
    <div class="col-span-4">
      <%= form.label :code_compte, style: "display: block" %>
      <%= form.number_field :code_compte, class: "w-full rounded-lg h-[35px]" %>
    </div>

    <div class="col-span-2">
      <%= form.label :solde, style: "display: block" %>
      <%= form.text_field :solde, value: 0, class: "w-full rounded-lg h-[35px]" %>
    </div>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/compte_clients/edit.html.erb
<h1>Editing compte client</h1>

<%= render "form", compte_client: @compte_client %>

<br>

<div>
  <%= link_to "Show this compte client", @compte_client %> |
  <%= link_to "Back to compte clients", compte_clients_path %>
</div>

app/views/compte_clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Compte clients</h1>

<div id="compte_clients">
  <% @compte_clients.each do |compte_client| %>
    <%= render compte_client %>
    <p>
      <%= link_to "Show this compte client", compte_client %>
    </p>
  <% end %>
</div>

<%= link_to "New compte client", new_compte_client_path %>

app/views/compte_clients/new.html.erb
<h1>New compte client</h1>

<%= render "form", compte_client: @compte_client %>

<br>

<div>
  <%= link_to "Back to compte clients", compte_clients_path %>
</div>

app/views/compte_clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @compte_client %>

<div>
  <%= link_to "Edit this compte client", edit_compte_client_path(@compte_client) %> |
  <%= link_to "Back to compte clients", compte_clients_path %>

  <%= button_to "Destroy this compte client", @compte_client, method: :delete %>
</div>