config/routes.rb
Rails.application.routes.draw do
  resources :virements
  resources :transactions
  resources :remboursements
  resources :credits
  resources :compte_clients
  resources :clients
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :client
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_action :set_credit, only: %i[ show edit update destroy ]

  # GET /credits or /credits.json
  def index
    @credits = Credit.all
  end

  # GET /credits/1 or /credits/1.json
  def show
  end

  # GET /credits/new
  def new
    @credit = Credit.new
  end

  # GET /credits/1/edit
  def edit
  end

  # POST /credits or /credits.json
  def create
    @credit = Credit.new(credit_params)

    respond_to do |format|
      if @credit.save
        format.html { redirect_to credit_url(@credit), notice: "Credit was successfully created." }
        format.json { render :show, status: :created, location: @credit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credits/1 or /credits/1.json
  def update
    respond_to do |format|
      if @credit.update(credit_params)
        format.html { redirect_to credit_url(@credit), notice: "Credit was successfully updated." }
        format.json { render :show, status: :ok, location: @credit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credits/1 or /credits/1.json
  def destroy
    @credit.destroy

    respond_to do |format|
      format.html { redirect_to credits_url, notice: "Credit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit
      @credit = Credit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def credit_params
      params.require(:credit).permit(:client_id, :montant, :taux_interet, :date_debut, :date_fin, :reste_non_paye)
    end
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/_card.html.erb
<div id="<%= dom_id credit %>">
  <p>
    <strong>Client:</strong>
    <%= credit.client_id %>
  </p>

  <p>
    <strong>Montant:</strong>
    <%= credit.montant %>
  </p>

  <p>
    <strong>Taux interet:</strong>
    <%= credit.taux_interet %>
  </p>

  <p>
    <strong>Date debut:</strong>
    <%= credit.date_debut %>
  </p>

  <p>
    <strong>Date fin:</strong>
    <%= credit.date_fin %>
  </p>

  <p>
    <strong>Reste non paye:</strong>
    <%= credit.reste_non_paye %>
  </p>

</div>

app/views/credits/_credit.html.erb
<tr id="<%= dom_id credit %>" class="border-b-[1px] border-gray-400 text-center text-[14px]">
  <td><%= credit.client.nom %></td>
  <td><%= credit.montant %></td>
  <td><%= credit.taux_interet %></td>
  <td><%= credit.date_debut %> - <%= credit.date_fin %></td>
  <td><%= credit.reste_non_paye %></td>
  <td>
    <%= link_to "Voir", credit, class: "rounded-lg py-[2px] px-2 text-white text-[12px] bg-blue-500 font-medium" %>
  </td>
</tr>

app/views/credits/_form.html.erb
<%= form_with(model: credit) do |form| %>
  <% if credit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(credit.errors.count, "error") %> prohibited this credit from being saved:</h2>

      <ul>
        <% credit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <%= form.text_field :client_id, class: "h-[30px] rounded shadow hidden" %>


  <div class="grid grid-cols-6 gap-4 w-full">
    <div class="col-span-3">
      <%= form.label :montant, style: "display: block" %>
      <%= form.text_field :montant, class: "h-[30px] rounded shadow w-full" %>
    </div>

    <div class="col-span-3">
      <%= form.label :taux_interet, style: "display: block" %>
      <%= form.text_field :taux_interet, class: "h-[30px] rounded shadow w-full" %>
    </div>
  </div>

  <div class="grid grid-cols-6 gap-4">
    <div class="col-span-3">
      <%= form.label :date_debut, style: "display: block" %>
      <%= form.date_field :date_debut, class: "h-[30px] rounded shadow" %>
    </div>

    <div class="col-span-3">
      <%= form.label :date_fin, style: "display: block" %>
      <%= form.date_field :date_fin, class: "h-[30px] rounded shadow" %>
    </div>
  </div>  

  <div>
    <%= form.label :reste_non_paye, style: "display: block" %>
    <%= form.text_field :reste_non_paye, class: "h-[30px] rounded shadow" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/credits/edit.html.erb
<h1>Editing credit</h1>

<%= render "form", credit: @credit %>

<br>

<div>
  <%= link_to "Show this credit", @credit %> |
  <%= link_to "Back to credits", credits_path %>
</div>

app/views/credits/index.html.erb
<div class="flex justify-between items-center px-4">
  <h1 class="text-xl font-[500]">Credits</h1>
  <%= link_to "Nouveau credit", new_credit_path, class: "py-3 text-[14px] text-blue-500 block font-medium" %>
</div>

<div id="credits" class="px-4">
  <table class="w-full">
    <thead>
      <tr class="border-b-[1px] border-gray-400">
        <th>Nom client</th>
        <th>Montant</th>
        <th>Interet</th>
        <th>Date</th>
        <th>Reste</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @credits.each do |credit| %>
        <%= render credit %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/credits/new.html.erb
<h1>New credit</h1>

<%= render "form", credit: @credit %>

<br>

<div>
  <%= link_to "Back to credits", credits_path %>
</div>

app/views/credits/show.html.erb
<%= render partial: "card", locals: { credit: @credit } %>

<div>
  <%= link_to "Edit this credit", edit_credit_path(@credit) %> |
  <%= link_to "Back to credits", credits_path %>

  <%= button_to "Destroy this credit", @credit, method: :delete %>
</div>