config/routes.rb
Rails.application.routes.draw do
  resources :virements
  resources :transactions
  resources :remboursements
  resources :credits
  resources :compte_clients
  resources :clients
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    getcompte = CompteClient.find(params[:compte_client_id])
    if getcompte
      getcompte.update("solde = solde + ?", params[:montant])
    end

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:type_transaction, :montant, :compte_client_id, :date_transaction)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_card.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Nom client:</strong>
    <%= transaction.type_transaction %>
  </p>
  <p>
    <strong>Type transaction:</strong>
    <%= transaction.type_transaction %>
  </p>

  <p>
    <strong>Montant:</strong>
    <%= transaction.montant %>
  </p>

  <p>
    <strong>Compte client:</strong>
    <%= transaction.compte_client_id %>
  </p>

  <p>
    <strong>Date transaction:</strong>
    <%= transaction.date_transaction %>
  </p>

</div>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="grid grid-cols-6 gap-4">
    
    <div class="col-span-3">
      <%= form.label :type_transaction, style: "display: block" %>
      <%= form.select :type_transaction, options_for_select([
        ["Dépot", "depot"],
        ["Retrait", "retrait"]
      ]), { include_blank: true }, class: "w-full rounded-lg h-[35px] shadow" %>
    </div>

    <div class="col-span-3">
      <%= form.label :montant, style: "display: block" %>
      <%= form.text_field :montant, class: "h-[30px] rounded shadow w-full" %>
    </div>
  </div>

  <div class="mb-2">
    <%= form.label :compte_client_id, style: "display: block" %>
    <%= form.text_field :compte_client_id, class: "h-[30px] rounded shadow" %>
  </div>

  <div class="mb-2">
    <%= form.label :compte_client_id, style: "display: block" %>
    <%= form.select :compte_client_id, CompteClient.all.collect { | compte | 
        [ "#{compte.client.nom} #{compte.client.prenom}", compte.id ] }, prompt: "Sélectionnez un client",  class: "w-full rounded-lg h-[35px] shadow" %>
  </div>

  <div class="mb-2">
    <%= form.label :date_transaction, style: "display: block" %>
    <%= form.date_field :date_transaction, class: "h-[30px] rounded shadow" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<tr id="<%= dom_id transaction %>" class="border-b-[1px] border-gray-400 text-center text-[14px]">
  <td>jerry nkafu</td>
  <td><%= transaction.type_transaction %></td>
  <td><%= transaction.montant %></td>
  <td><%= transaction.compte_client.numero_compte %></td>
  <td><%= transaction.date_transaction %></td>
  <td>
    <%= link_to "Voir", transaction, class: "rounded-lg py-[2px] px-2 text-white text-[12px] bg-blue-500 font-medium" %>
  </td>
</tr>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<div class="flex justify-between items-center px-4">
  <h1 class="text-xl font-[500]">Transactions</h1>
  <%= link_to "Nouveau transaction", new_transaction_path, class: "py-3 text-[14px] text-blue-500 block font-medium" %>
</div>

<div id="transactions" class="px-4">
  <table class="w-full">
    <thead>
      <tr class="border-b-[1px] border-gray-400">
        <th>Nom client</th>
        <th>Transaction</th>
        <th>Montant</th>
        <th>Num compte</th>
        <th>Date</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @transactions.each do |transaction| %>
        <%= render transaction %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/show.html.erb
<%= render partial: "card", locals: { transaction: @transaction } %>

<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>

  <%= button_to "Destroy this transaction", @transaction, method: :delete %>
</div>