config/routes.rb
Rails.application.routes.draw do
  resources :virements
  resources :transactions
  resources :remboursements
  resources :credits
  resources :compte_clients
  resources :clients
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :virements
    has_many :credits
    has_many :compte_clients
end

app/models/compte_client.rb
class CompteClient < ApplicationRecord
  belongs_to :client
  has_many :transactions
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :client
end

app/models/remboursement.rb
class Remboursement < ApplicationRecord
  belongs_to :credit
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :compte_client
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/virement.rb
class Virement < ApplicationRecord
  belongs_to :emeteur, class_name: 'CompteClient'
  belongs_to :receveur, class_name: 'CompteClient'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_devise_parameters, if: :devise_controller?
    def configure_devise_parameters
        devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:username, :email, :password, :password_confirmation)}
    end
    
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
    @client = Client.find(params[:id]) # Assurez-vous de récupérer le client
    @virement = Virement.new
    @transaction = Transaction.new
    @compte = CompteClient.find(1)
    @compte_client = @client.compte_clients.build
    @credit = @client.credits.build 
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:nom, :prenom, :telephone, :adress, :email)
    end
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_action :set_credit, only: %i[ show edit update destroy ]

  # GET /credits or /credits.json
  def index
    @credits = Credit.all
  end

  # GET /credits/1 or /credits/1.json
  def show
  end

  # GET /credits/new
  def new
    @credit = Credit.new
  end

  # GET /credits/1/edit
  def edit
  end

  # POST /credits or /credits.json
  def create
    @credit = Credit.new(credit_params)

    respond_to do |format|
      if @credit.save
        format.html { redirect_to credit_url(@credit), notice: "Credit was successfully created." }
        format.json { render :show, status: :created, location: @credit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credits/1 or /credits/1.json
  def update
    respond_to do |format|
      if @credit.update(credit_params)
        format.html { redirect_to credit_url(@credit), notice: "Credit was successfully updated." }
        format.json { render :show, status: :ok, location: @credit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credits/1 or /credits/1.json
  def destroy
    @credit.destroy

    respond_to do |format|
      format.html { redirect_to credits_url, notice: "Credit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit
      @credit = Credit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def credit_params
      params.require(:credit).permit(:client_id, :montant, :taux_interet, :date_debut, :date_fin, :reste_non_paye)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        @credits = Credit.all
        @transactions = Transaction.all
    end    

end

app/controllers/virements_controller.rb
class VirementsController < ApplicationController
  before_action :set_virement, only: %i[ show edit update destroy ]

  # GET /virements or /virements.json
  def index
    @virements = Virement.all
  end

  # GET /virements/1 or /virements/1.json
  def show
  end

  # GET /virements/new
  def new
    @virement = Virement.new
  end

  # GET /virements/1/edit
  def edit
  end

  # POST /virements or /virements.json
  def create
    @virement = Virement.new(virement_params)

    respond_to do |format|
      if @virement.save
        CompteClient.where(id: params[:receveur_id]).update("solde = solde + ?", params[:montant])
        format.html { redirect_to virement_url(@virement), notice: "Virement was successfully created." }
        format.json { render :show, status: :created, location: @virement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @virement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /virements/1 or /virements/1.json
  def update
    respond_to do |format|
      if @virement.update(virement_params)
        format.html { redirect_to virement_url(@virement), notice: "Virement was successfully updated." }
        format.json { render :show, status: :ok, location: @virement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @virement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /virements/1 or /virements/1.json
  def destroy
    @virement.destroy

    respond_to do |format|
      format.html { redirect_to virements_url, notice: "Virement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_virement
      @virement = Virement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def virement_params
      params.require(:virement).permit(:montant, :date_jour, :emeteur_id, :receveur_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/compte_clients_helper.rb
module CompteClientsHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/remboursements_helper.rb
module RemboursementsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/virements_helper.rb
module VirementsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Banque</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-[#F0F2F5]">
    
    <% if !user_signed_in? %>
      <div class="h-[60px] flex justify-between items-center px-4">
        <div class="text-xl font-[500]">banqueGEST</div>
        <div class="rightnav">
          <%= link_to 'connexion', new_user_session_path, class: 'linkbtn' %>
        </div>
      </div>
      <div class="text-center">
        <p class="text-[20px]">Examen AOSCC system banquaire</p>
      </div>
      <%= yield %>
    <% else %>
      <div class="bg-gray-900 flex justify-between items-center h-[60px] px-4 ">
        <div class="text-xl text-white font-[500]">banqueGEST</div>
        <div class="text-gray-300">
          <%= link_to "#{current_user.username}", destroy_user_session_path, method: :delete, class: 'rounded-lg block font-[200]' %>
          <%=  %>
        </div>
      </div>
      <div class="m-auto container bg-white min-h-[90vh] h-auto px-4">
      <div class="flex justify-center text-blue-500 h-[40px] items-center">
        <div class="flex items-center">
          <%= fa_icon "home" %> 
          <%= link_to 'Accueil', root_path, class: 'ml-[5px]' %>
        </div>
        <div class="mx-4 text-xl flex items-center">.</div>
        <div class="flex items-center">
          <%= fa_icon "user" %> 
          <%= link_to 'Clients', clients_path, class: 'ml-[5px]' %>
        </div>
        <div class="mx-4 text-xl flex items-center">.</div>
        <div class="">
          <%= fa_icon "credit-card" %> 
          <%= link_to 'Credits', credits_path, class: 'ml-[5px]' %>
        </div>
        <div class="mx-4 text-xl flex items-center">.</div>
        <div class="">
          <%= fa_icon "money" %> 
          <%= link_to 'Transactions', transactions_path, class: 'ml-[5px]' %>
        </div>
        <div class="mx-4 text-xl flex items-center">.</div>
        <div class="">
          <%= fa_icon "arrow-right" %> 
          <%= link_to 'Virements', virements_path, class: 'ml-[5px]' %>
        </div>
      </div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <% end %>
    
    
  </body>
</html>